<a href="https://colab.research.google.com/github/hitarthi45/Artificial-Intelligence/blob/main/(EXP_8)sentence_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#3 sentence toward country, 2 sentence towards sports, 2 sentence towards technology
Sentences =[ " India is my country. All indians are my brothers and sisters",
             " India is country of herbs and spices.",
             " India is known for its rich and varied heritage.",

             " I like to see cricket and football.",
             " Cricket has many talented cricketers like Virat kohli and Rohit sharma.",

             " Now-a-days the technology is growing very fast.",
             " AI industry is taking place in the  market rapidly." ]

In [ ]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer #TF-bow
from sklearn.feature_extraction.text import TfidfVectorizer #TF-IDF
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
#embeddings using TF-bow
tf_vectorizer = CountVectorizer()
tf_matrix=tf_vectorizer.fit_transform(Sentences)

In [ ]:
tf_matrix

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 60 stored elements and shape (7, 46)>

In [ ]:
tf_similarity=cosine_similarity(tf_matrix)
tf_similarity

array([[1.        , 0.41931393, 0.2773501 , 0.1132277 , 0.0836242 ,
        0.09805807, 0.09245003],
       [0.41931393, 1.        , 0.37796447, 0.15430335, 0.11396058,
        0.13363062, 0.12598816],
       [0.2773501 , 0.37796447, 1.        , 0.13608276, 0.10050378,
        0.11785113, 0.11111111],
       [0.1132277 , 0.15430335, 0.13608276, 1.        , 0.36927447,
        0.        , 0.        ],
       [0.0836242 , 0.11396058, 0.10050378, 0.36927447, 1.        ,
        0.        , 0.        ],
       [0.09805807, 0.13363062, 0.11785113, 0.        , 0.        ,
        1.        , 0.23570226],
       [0.09245003, 0.12598816, 0.11111111, 0.        , 0.        ,
        0.23570226, 1.        ]])

In [ ]:
#embeddings using TF-idf
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix=tfidf_vectorizer.fit_transform(Sentences)
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 60 stored elements and shape (7, 46)>

In [ ]:
tfidf_similarity=cosine_similarity(tfidf_matrix)
tfidf_similarity

array([[1.        , 0.24744312, 0.12426562, 0.04105246, 0.02852771,
        0.033576  , 0.03140191],
       [0.24744312, 1.        , 0.186671  , 0.06166874, 0.04285414,
        0.05043765, 0.04717175],
       [0.12426562, 0.186671  , 1.        , 0.05062327, 0.03517855,
        0.04140377, 0.03872283],
       [0.04105246, 0.06166874, 0.05062327, 1.        , 0.24843073,
        0.        , 0.        ],
       [0.02852771, 0.04285414, 0.03517855, 0.24843073, 1.        ,
        0.        , 0.        ],
       [0.033576  , 0.05043765, 0.04140377, 0.        , 0.        ,
        1.        , 0.13133623],
       [0.03140191, 0.04717175, 0.03872283, 0.        , 0.        ,
        0.13133623, 1.        ]])

In [ ]:
#finding document similarity
def doc_sim(similarity_matrix,Sentences):
  for i in range(len(Sentences)):
    sims=similarity_matrix[i].copy()
    sims[i]=-1
    top_index=np.argmax(sims)
    print(Sentences[i],"-->",Sentences[top_index])

In [ ]:
doc_sim(tfidf_similarity,Sentences)

 India is my country. All indians are my brothers and sisters -->  India is country of herbs and spices.
 India is country of herbs and spices. -->  India is my country. All indians are my brothers and sisters
 India is known for its rich and varied heritage. -->  India is country of herbs and spices.
 I like to see cricket and football. -->  Cricket has many talented cricketers like Virat kohli and Rohit sharma.
 Cricket has many talented cricketers like Virat kohli and Rohit sharma. -->  I like to see cricket and football.
 Now-a-days the technology is growing very fast. -->  AI industry is taking place in the  market rapidly.
 AI industry is taking place in the  market rapidly. -->  Now-a-days the technology is growing very fast.


### POST LAB


In [ ]:
documents = [
    Sentences[0], # "India is my country. All indians are my brothers and sisters"
    Sentences[1], # "India is country of herbs and spices."
    Sentences[2]  # "India is known for its rich and varied heritage."
]

print("Documents selected:")
for i, doc in enumerate(documents):
    print(f"Document {i+1}: {doc}")

Documents selected:
Document 1:  India is my country. All indians are my brothers and sisters
Document 2:  India is country of herbs and spices.
Document 3:  India is known for its rich and varied heritage.


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# BoW Vectorization
bow_vectorizer = CountVectorizer()
bow_matrix = bow_vectorizer.fit_transform(documents)

print("BoW Matrix (Term Frequencies):")
print(bow_matrix.toarray())
print("\nFeatures (Vocabulary):")
print(bow_vectorizer.get_feature_names_out())

# Calculate Cosine Similarity for BoW
bow_similarity = cosine_similarity(bow_matrix)

print("\nBoW Similarity Matrix:")
print(bow_similarity)

BoW Matrix (Term Frequencies):
[[1 1 1 1 1 0 0 0 1 1 1 0 0 2 0 0 1 0 0]
 [0 1 0 0 1 0 1 0 1 0 1 0 0 0 1 0 0 1 0]
 [0 1 0 0 0 1 0 1 1 0 1 1 1 0 0 1 0 0 1]]

Features (Vocabulary):
['all' 'and' 'are' 'brothers' 'country' 'for' 'herbs' 'heritage' 'india'
 'indians' 'is' 'its' 'known' 'my' 'of' 'rich' 'sisters' 'spices' 'varied']

BoW Similarity Matrix:
[[1.         0.41931393 0.2773501 ]
 [0.41931393 1.         0.37796447]
 [0.2773501  0.37796447 1.        ]]


In [ ]:
# TF Vectorization (same as BoW with CountVectorizer)
tf_vectorizer = CountVectorizer()
tf_matrix = tf_vectorizer.fit_transform(documents)

print("TF Matrix (Term Frequencies):")
print(tf_matrix.toarray())

# Calculate Cosine Similarity for TF
tf_similarity = cosine_similarity(tf_matrix)

print("\nTF Similarity Matrix:")
print(tf_similarity)

TF Matrix (Term Frequencies):
[[1 1 1 1 1 0 0 0 1 1 1 0 0 2 0 0 1 0 0]
 [0 1 0 0 1 0 1 0 1 0 1 0 0 0 1 0 0 1 0]
 [0 1 0 0 0 1 0 1 1 0 1 1 1 0 0 1 0 0 1]]

TF Similarity Matrix:
[[1.         0.41931393 0.2773501 ]
 [0.41931393 1.         0.37796447]
 [0.2773501  0.37796447 1.        ]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# TF-IDF Vectorization
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

print("TF-IDF Matrix:")
print(tfidf_matrix.toarray())
print("\nFeatures (Vocabulary):")
print(tfidf_vectorizer.get_feature_names_out())

# Calculate Cosine Similarity for TF-IDF
tfidf_similarity = cosine_similarity(tfidf_matrix)

print("\nTF-IDF Similarity Matrix:")
print(tfidf_similarity)

TF-IDF Matrix:
[[0.3067877  0.18119376 0.3067877  0.3067877  0.23331996 0.
  0.         0.         0.18119376 0.3067877  0.18119376 0.
  0.         0.61357541 0.         0.         0.3067877  0.
  0.        ]
 [0.         0.27463443 0.         0.         0.35364183 0.
  0.46499651 0.         0.27463443 0.         0.27463443 0.
  0.         0.         0.46499651 0.         0.         0.46499651
  0.        ]
 [0.         0.22249441 0.         0.         0.         0.37671579
  0.         0.37671579 0.22249441 0.         0.22249441 0.37671579
  0.37671579 0.         0.         0.37671579 0.         0.
  0.37671579]]

Features (Vocabulary):
['all' 'and' 'are' 'brothers' 'country' 'for' 'herbs' 'heritage' 'india'
 'indians' 'is' 'its' 'known' 'my' 'of' 'rich' 'sisters' 'spices' 'varied']

TF-IDF Similarity Matrix:
[[1.         0.23179783 0.1209438 ]
 [0.23179783 1.         0.18331388]
 [0.1209438  0.18331388 1.        ]]
